[tool.poetry]
name = "project-ml-billing-service"
version = "0.1.0"
description = ""
authors = ["Mikhail Repkin"]

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.25"}
fastapi = "^0.108.0"
uvicorn = "^0.25.0"
black = "^23.12.1"
passlib = "^1.7.4"
python-jose = "^3.3.0"
pydantic-settings = "^2.1.0"
python-multipart = "^0.0.6"
bcrypt = "3.2.2"
pandas = "^2.1.4"
joblib = "1.3.2"
rq = "^1.15.1"
httpx = "^0.26.0"
pytest = "^7.4.4"
aiosqlite = "^0.19.0"
pytest-asyncio = "^0.23.3"
anyio = "^4.2.0"
scikit-learn = "1.2.2"
redis = "^5.0.1"
streamlit = "^1.30.0"

[tool.poetry.dev-dependencies]
flake8 = "^6.1.0"
ipykernel = "^6.28.0"
pytest-asyncio = "^0.23.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
